version: '3.8'

services:
  django:
    build: . 
    ports:
      - "8000:8000"  
    environment:
      - DJANGO_SETTINGS_MODULE=OdooAli.settings  
      - POSTGRES_NAME=warehouse_db  
      - POSTGRES_USER=your_db_user  
      - POSTGRES_PASSWORD=your_db_password  
      - POSTGRES_HOST=db  
      - POSTGRES_PORT=5432  
      - ./OdooAli:/app/OdooAli  
      - ./requirements.txt:/app/requirements.txt  
      - ./static:/app/static  
      - ./templates:/app/templates  
    depends_on:
      - postgres  

  postgres:
    image: postgres:14-alpine  
    environment:
      - POSTGRES_DB=warehouse_db  
      - POSTGRES_USER=your_db_user  
      - POSTGRES_PASSWORD=your_db_password  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  
    restart: always 

volumes:
  postgres_data: