global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['django_web:8000']

  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['react_frontend:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


rule_files:
  - "/etc/prometheus/alert_rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
