version: '3.9'

services:
  db:
    image: postgres:15
    container_name: django_db
    env_file:
      - .env
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_web
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react_frontend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: odooali_nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - frontend
    restart: unless-stopped


volumes:
  postgres_data:
